# Licensed under the Apache-2.0 license

[package]
name = "registers-generated"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tock-registers.workspace = true
