# Licensed under the Apache-2.0 license

[workspace]
members = [
    "common/pldm",
    "emulator/app",
    "emulator/bmc/pldm-fw-pkg",
    "emulator/bus",
    "emulator/caliptra",
    "emulator/compliance-test",
    "emulator/cpu",
    "emulator/derive",
    "emulator/periph",
    "emulator/types",
    "registers/generated-emulator",
    "registers/generated-firmware",
    "registers/generator",
    "registers/systemrdl",
    "rom",
    "romtime",
    "runtime",
    "runtime/apps/api",
    "runtime/apps/example",
    "runtime/apps/libtock/apis/interface/buttons",
    "runtime/apps/libtock/apis/interface/buzzer",
    "runtime/apps/libtock/apis/interface/console",
    "runtime/apps/libtock/apis/interface/leds",
    "runtime/apps/libtock/apis/kernel/low_level_debug",
    "runtime/apps/libtock/apis/peripherals/adc",
    "runtime/apps/libtock/apis/peripherals/alarm",
    "runtime/apps/libtock/apis/peripherals/gpio",
    "runtime/apps/libtock/apis/peripherals/i2c_master",
    "runtime/apps/libtock/apis/peripherals/i2c_master_slave",
    "runtime/apps/libtock/apis/peripherals/rng",
    "runtime/apps/libtock/apis/sensors/air_quality",
    "runtime/apps/libtock/apis/sensors/ambient_light",
    "runtime/apps/libtock/apis/sensors/ninedof",
    "runtime/apps/libtock/apis/sensors/proximity",
    "runtime/apps/libtock/apis/sensors/temperature",
    "runtime/apps/libtock/apis/storage/key_value",
    "runtime/apps/libtock/panic_handlers/debug_panic",
    "runtime/apps/libtock/panic_handlers/small_panic",
    "runtime/apps/libtock/platform",
    "runtime/apps/libtock/runner",
    "runtime/apps/libtock/runtime",
    "runtime/apps/libtock/syscalls_tests",
    "runtime/apps/libtock/tools/print_sizes",
    "runtime/apps/libtock/ufmt",
    "runtime/apps/libtock/unittest",
    "runtime/apps/libtockasync",
    "runtime/apps/spdm/spdm-app",
    "runtime/apps/spdm/spdm-lib",
    "runtime/apps/syscall",
    "runtime/capsules",
    "runtime/i3c",
    "tests/hello",
    "tests/integration",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Caliptra contributors"]

[workspace.dependencies]
bitfield = "0.14.0"
bit-vec = "0.6.3"
chrono = {version = "0.4.38", features = ["serde"]}
clap = { version = "4.5.23", features = [
    "cargo",
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
crc = "3.2.1"
crc32fast = "1.4.2"
critical-section = "1.1.2"
crossterm = "0.28.1"
ctrlc = "3.4.5"
elf = "0.7.4"
ecdsa = { version = "0.16.9", features = ["pem"]}
embassy-executor = { version = "0.6.3", features = ["nightly"] }
embedded-alloc = "0.5.1"
futures = "0.3.31"
gdbstub = "0.6.3"
gdbstub_arch = "0.2.4"
getrandom = "0.2"
hex = "0.4.3"
lazy_static = "1.4.0"
num_enum = "0.7.2"
num-derive = "0.4.2"
num-traits = "0.2"
portable-atomic = "1.7.0"
p384 = "0.13.0"
proc-macro2 = "1.0.66"
quote = "1.0"
rand = "0.8.5"
semver = "1.0.23"
sec1 = { version = "0.7.3" }
serde = { version = "1.0.209", features = ["alloc", "derive", "serde_derive"] }
serde_json = { version = "1.0.127", features = ["alloc"] }
serde-hjson = "1.1.0"
sha2 = "0.10.8"
smlang = "0.8.0"
sudo = "0.6.0"
strum = "0.24"
strum_macros = "0.24"
tempfile = "3.14.0"
thiserror-no-std = "2.0.2"
toml = "0.8.19"
uuid = { version = "1.10.0", features = ["serde"]}
walkdir = "2.5.0"
zerocopy = { version = "0.8.8", features = ["derive"] }
zeroize = { version = "1.6.0", default-features = false, features = ["zeroize_derive"] }

# local dependencies
capsules-runtime = { path = "runtime/capsules" }
emulator-bmc = { path = "emulator/bmc" }
emulator-bus = { path = "emulator/bus" }
emulator-caliptra = { "path" = "emulator/caliptra" }
emulator-cpu = { path = "emulator/cpu" }
emulator-derive = { path = "emulator/derive" }
emulator-periph = { path = "emulator/periph" }
emulator-registers-generated = { path = "registers/generated-emulator" }
emulator-types = { path = "emulator/types" }
flash-driver = { path = "runtime/flash" }
i3c-driver = { path = "runtime/i3c" }
libtockasync = { path = "runtime/apps/libtockasync" }
pldm-common = { path = "common/pldm"}
registers-generated = { path = "registers/generated-firmware" }
registers-generator = { path = "registers/generator" }
registers-systemrdl = { path = "registers/systemrdl" }
romtime = { path = "romtime" }

# App related dependencies
spdm-lib = { path = "runtime/apps/spdm/spdm-lib" }

# libtock dependencies
libtock = { path = "runtime/apps/libtock" }
libtock_alarm = { path = "runtime/apps/libtock/apis/peripherals/alarm" }
libtock_console = { path = "runtime/apps/libtock/apis/interface/console" }
libtock_debug_panic = { path = "runtime/apps/libtock/panic_handlers/debug_panic" }
libtock_platform = { path = "runtime/apps/libtock/platform" }
libtock_runtime = { path = "runtime/apps/libtock/runtime" }
libtock_unittest = { path = "runtime/apps/libtock/unittest" }
libsyscall-caliptra = { path = "runtime/apps/syscall" }
libapi-caliptra = { path = "runtime/apps/api" }


# caliptra dependencies; keep git revs in sync
caliptra-api-types = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-builder = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-emu-bus = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-emu-cpu = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-emu-periph = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-emu-types = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-hw-model = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-image-crypto = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5", default-features = false, features = ["rustcrypto"] }
caliptra-image-gen = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-registers = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-image-types = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }
caliptra-test = { git = "https://github.com/chipsalliance/caliptra-sw", rev = "aec9434c1b42ebe77ae553c884006f9449ad5eb5" }

# tock dependencies; keep git revs in sync
capsules-core = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
capsules-extra = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
capsules-system = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
components = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
kernel = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
riscv = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
riscv-csr = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
rv32i = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }
tock-registers = { git = "https://github.com/tock/tock.git", rev = "b128ae817b86706c8c4e39d27fae5c54b98659f1" }


# Always optimize the emulator during tests, as it is a major bottleneck for
# test speed.
[profile.test.package.emulator-bus]
opt-level = 3
[profile.test.package.emulator-cpu]
opt-level = 3
[profile.test.package.emulator-periph]
opt-level = 3
[profile.test.package.emulator-types]
opt-level = 3
[profile.test.package.tock-registers]
opt-level = 3

[profile.release]
debug = true      # Keep debug symbols in the release ELF so that we can debug more easily.
lto = true
opt-level = "s"
codegen-units = 1
