# Licensed under the Apache-2.0 license

[toolchain]
channel = "1.85"
components = ["clippy", "rust-src", "llvm-tools", "rustfmt", "rustc-dev"]
targets = [
  "x86_64-unknown-linux-gnu",
  "riscv32imc-unknown-none-elf",
  "aarch64-unknown-linux-gnu",
]
profile = "default"
