# Licensed under the Apache-2.0 license

[package]
name = "mcu-runtime-emulator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
arrayvec.workspace = true
capsules-core.workspace = true
capsules-extra.workspace = true
capsules-emulator.workspace = true
capsules-runtime.workspace = true
capsules-system.workspace = true
components.workspace = true
doe-mbox-driver.workspace = true
dma-driver.workspace = true
flash-driver.workspace = true
i3c-driver.workspace = true
kernel.workspace = true
mcu-components.workspace = true
mcu-config.workspace = true
mcu-config-emulator.workspace = true
mcu-tock-veer.workspace = true
registers-generated.workspace = true
romtime.workspace = true
tock-registers.workspace = true

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv-csr.workspace = true
riscv.workspace = true
rv32i.workspace = true

[features]
default = []
test-caliptra-certs = []
test-caliptra-crypto = []
test-caliptra-mailbox = []
test-dma = []
test-exit-immediately = []
test-i3c-simple = []
test-i3c-constant-writes = []
test-flash-based-boot = []
test-flash-ctrl-init = []
test-flash-ctrl-read-write-page = []
test-flash-ctrl-erase-page = []
test-flash-storage-read-write = []
test-flash-storage-erase = []
test-flash-usermode = []
test-mctp-ctrl-cmds = []
test-mctp-capsule-loopback = []
test-mctp-user-loopback = []
test-mcu-rom-flash-access = []
test-pldm-request-response = []
test-pldm-discovery = []
test-pldm-fw-update = []
test-pldm-fw-update-e2e = []
test-pldm-streaming-boot = []
test-spdm-validator = []
