# Licensed under the Apache-2.0 license

[package]
name = "i3c-driver"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
capsules-core.workspace = true
kernel.workspace = true
registers-generated.workspace = true
romtime.workspace = true
rv32i.workspace = true
tock-registers.workspace = true
