# Licensed under the Apache-2.0 license

[package]
name = "mcu-rom-fpga"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
mcu-builder.workspace = true
mcu-config-fpga.workspace = true

[dependencies]
mcu-config.workspace = true
mcu-config-fpga.workspace = true
mcu-rom-common.workspace = true
registers-generated.workspace = true
romtime.workspace = true
tock-registers.workspace = true
zeroize.workspace = true

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv-csr.workspace = true
rv32i.workspace = true

[features]
core_test = ["mcu-rom-common/core_test"]
