# Licensed under the Apache-2.0 license

[package]
name = "mcu-mbox-driver"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
capsules-core.workspace = true
mcu-mbox-comm.workspace = true
kernel.workspace = true
registers-generated.workspace = true
romtime.workspace = true
