# Licensed under the Apache-2.0 license

[package]
name = "flash-driver"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel.workspace = true

[target.'cfg(target_arch = "riscv32")'.dependencies]
capsules-core.workspace = true
registers-generated.workspace = true
romtime.workspace = true
tock-registers.workspace = true
