# Licensed under the Apache-2.0 license

[package]
name = "libtockasync"
description = "Async executor and tools for applications running under Tock"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
critical-section.workspace = true
embassy-executor.workspace = true
libtock.workspace = true
libtock_console.workspace = true
libtock_debug_panic.workspace = true
libtock_platform.workspace = true
libtock_runtime.workspace = true
portable-atomic.workspace = true

[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
libtock_unittest.workspace = true

[target.'cfg(target_arch = "riscv32")'.dependencies]
embassy-executor = { version = "0.9.1", features = ["arch-riscv32"] }
embedded-alloc.workspace = true
