# Licensed under the Apache-2.0 license

[package]
name = "doe-mbox-driver"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
capsules-core.workspace = true
doe-transport.workspace = true
kernel.workspace = true
registers-generated.workspace = true