# Licensed under the Apache-2.0 license

name: FPGA Tests

on:
  pull_request:
  workflow_dispatch:
jobs:
  build_test_binaries:
    runs-on: [e2-standard-8]
    timeout-minutes: 60
    env:
      SCCACHE_VERSION: 0.10.0
      SCCACHE_GHA_CACHE_TO: sccache-caliptra-mcu-sw
      SCCACHE_GHA_CACHE_FROM: sccache-caliptra-mcu-sw
      SCCACHE_GHA_ENABLED: "on"
      # Change this to a new random value if you suspect the cache is corrupted
      CACHE_BUSTER: 9ff0ac869868
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install cross compiler
        run: |
          sudo apt-get update -qy && sudo apt-get install -y gcc-aarch64-linux-gnu squashfs-tools
          rustup toolchain install 1.84-x86_64-unknown-linux-gnu
          rustup target add riscv32imc-unknown-none-elf
          rustup target add aarch64-unknown-linux-gnu

      - name: Restore sccache binary
        uses: actions/cache/restore@v3
        id: sccache_bin_restore
        with:
          path: ~/.cargo/bin/sccache
          key: sccache-bin-${{ env.SCCACHE_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Install sccache
        if: steps.sccache_bin_restore.outputs.cache-hit != 'true'
        run: |
          rustup install 1.85
          cargo +1.85 install sccache --version ${SCCACHE_VERSION} --no-default-features --features=gha --locked

      # Save the sccache binary immediately so we can reuse it in future runs
      # even if the rest of the current run fails.
      - name: Save sccache binary
        uses: actions/cache/save@v3
        if: steps.sccache_bin_restore.outputs.cache-hit != 'true'
        with:
          path: ~/.cargo/bin/sccache
          key: ${{ steps.sccache_bin_restore.outputs.cache-primary-key }}

      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('RUSTC_WRAPPER', process.env.HOME + '/.cargo/bin/sccache');
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('ACTIONS_CACHE_SERVICE_V2', 'on');

      - name: Restore openssl from cache
        uses: actions/cache/restore@v3
        id: restore_openssl_cache
        with:
          path: /tmp/openssl.tar
          key: openssl-${{ env.CACHE_BUSTER }}

      - name: Extract openssl
        if: "steps.restore_openssl_cache.outputs.cache-hit"
        run: |
          sudo tar -xvPf /tmp/openssl.tar

      - name: Build OpenSSL
        if: "!steps.restore_openssl_cache.outputs.cache-hit"
        run: |
          curl -L "https://github.com/openssl/openssl/releases/download/openssl-3.5.2/openssl-3.5.2.tar.gz" -o openssl.tar.gz
          OPENSSL_SHA256="c53a47e5e441c930c3928cf7bf6fb00e5d129b630e0aa873b08258656e7345ec"
          if ! (echo "${OPENSSL_SHA256} openssl.tar.gz" | sha256sum -c); then
            echo "OpenSSL tarball was an unexpected hash."
            exit 1
          fi

          tar -xvf openssl.tar.gz

          # For some reason make clean is not fully cleaning up the previous build
          # so create a duplicate folder
          cp -r openssl-3.5.2 openssl-3.5.2-arm

          pushd openssl-3.5.2
          ./config no-shared no-apps no-quic
          make -j8 build_sw
          popd

          pushd openssl-3.5.2-arm
          export CROSS_COMPILE="aarch64-linux-gnu-"
          ./config linux-aarch64 no-shared no-apps no-quic --cross-compile-prefix="${CROSS_COMPILE}"
          make -j8 build_sw
          popd

          mkdir -p /tmp/openssl/native/lib
          mv openssl-3.5.2/include /tmp/openssl/native/include
          mv openssl-3.5.2/libcrypto.a /tmp/openssl/native/lib
          mv openssl-3.5.2/libssl.a /tmp/openssl/native/lib

          mkdir -p /tmp/openssl/arm/lib
          mv openssl-3.5.2-arm/include /tmp/openssl/arm/include
          mv openssl-3.5.2-arm/libcrypto.a /tmp/openssl/arm/lib
          mv openssl-3.5.2-arm/libssl.a /tmp/openssl/arm/lib

          sudo tar cvf /tmp/openssl.tar -P /tmp/openssl

      - name: Save openssl to cache
        if: "!steps.restore_openssl_cache.outputs.cache-hit"
        uses: actions/cache/save@v3
        with:
          path: /tmp/openssl.tar
          key: openssl-${{ env.CACHE_BUSTER }}

      - name: Build test firmware
        run: |
          # In the CI we really want to avoid lengthy build steps.
          # Vendoring OpenSSL is a huge time sink, and instead linking a prebuilt
          # OpenSSL reduces build speeds.
          export OPENSSL_NO_VENDOR=true
          export OPENSSL_STATIC=true
          export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR=/tmp/openssl/native
          export AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR=/tmp/openssl/arm

          # Cross compile for the ARM core
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER="aarch64-linux-gnu-gcc"

          # Build ROM and runtime binaries
          echo "Cross compiling FPGA binaries"
          cargo xtask-fpga all-build --platform fpga \
            --runtime-features test-mctp-capsule-loopback \
            --separate-runtimes
          sccache --show-stats

          mkdir -p /tmp/caliptra-binaries
          tar -cvz -f /tmp/caliptra-binaries/caliptra-binaries.tar.gz \
            target/all-fw.zip

          echo "Cross compiling test binaries"
          FEATURES="fpga_realtime"
          cargo nextest archive \
            --features=${FEATURES} \
            --release \
            --target=aarch64-unknown-linux-gnu \
            --archive-file=/tmp/caliptra-test-binaries.tar.zst
          sccache --show-stats

          mkdir /tmp/caliptra-test-binaries/
          tar xvf /tmp/caliptra-test-binaries.tar.zst -C /tmp/caliptra-test-binaries/
          mksquashfs /tmp/caliptra-test-binaries /tmp/caliptra-test-binaries.sqsh -comp zstd

      - name: 'Upload test binaries artifact'
        uses: actions/upload-artifact@v4
        with:
          name: caliptra-test-binaries${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-test-binaries.sqsh
          retention-days: 1

      - name: 'Upload test firmware artifact'
        uses: actions/upload-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries
          retention-days: 1

  test_artifacts:
    runs-on: vck190-subsystem-2.0
    needs: build_test_binaries
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: 'Download Test Binaries Artifact'
        uses: actions/download-artifact@v4
        with:
          name: caliptra-test-binaries${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-test-binaries.sqsh

      - name: 'Download Test Firmware Artifact'
        uses: actions/download-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries

      - name: Mount binaries
        run: |
          tar -xvf /tmp/caliptra-binaries/caliptra-binaries.tar.gz

          sudo mkdir /tmp/caliptra-test-binaries
          echo mount squashfs
          sudo mount /tmp/caliptra-test-binaries.sqsh/caliptra-test-binaries.sqsh /tmp/caliptra-test-binaries -t squashfs -o loop
          find /tmp/caliptra-test-binaries

      - name: Execute tests
        run: |
          export RUST_BACKTRACE=1
          export RUST_TEST_THREADS=1
          TEST_BIN=/tmp/caliptra-test-binaries

          COMMON_ARGS=(
              --cargo-metadata="${TEST_BIN}/target/nextest/cargo-metadata.json"
              --binaries-metadata="${TEST_BIN}/target/nextest/binaries-metadata.json"
              --target-dir-remap="${TEST_BIN}/target"
              --workspace-remap=.
              -E 'package(mcu-hw-model) - test(model_emulated::test::test_new_unbooted)'
              -E 'package(tests-integration) and test(test_jtag_taps)'
              -E 'package(tests-integration) and test(test_lc_transitions)'
              -E 'package(tests-integration) and test(test_uds)' # Modify this as we onboard crates to the FPGA test suite.
          )
              # disabled for now due to flakiness of recovery boot
              # -E 'package(tests-integration) and test(test_mctp_capsule_loopback)'


          cargo-nextest nextest list \
              "${COMMON_ARGS[@]}" \
              --message-format json > /tmp/nextest-list.json

          sudo CPTRA_FIRMWARE_BUNDLE="${PWD}/target/all-fw.zip" cargo-nextest nextest run \
              "${COMMON_ARGS[@]}" \
              --test-threads=${RUST_TEST_THREADS} \
              --no-fail-fast \
              --profile=nightly

      - name: 'Upload test results'
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: caliptra-test-results${{ inputs.artifact-suffix }}
          path: |
            /tmp/junit.xml
            /tmp/nextest-list.json
