# Licensed under the Apache-2.0 license

[package]
name = "pldm-common"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
zerocopy.workspace = true
bitfield.workspace = true

